spring:
  application:
    name: lms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/apaspxp/configuration.git
          default-label: master
server:
  port: 5555
