-- liquibase formatted sql

-- changeset rajes:1678898835087-8
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'LMSATTENDANCESERVICE' AND table_name = 'LEAVE_ENTITLEMENT';
CREATE TABLE LEAVE_ENTITLEMENT (
    EMPLOYEE_ID VARCHAR(255) PRIMARY KEY,
    SICK_LEAVE_BALANCE INT,
    SICK_LEAVE_ENTITLE INT,
    CASUAL_LEAVE_BALANCE INT,
    CASUAL_LEAVE_ENTITLE INT,
    EARNED_LEAVE_BALANCE INT ,
    EARNED_LEAVE_ENTITLE INT,
    PATERNITY_LEAVE_BALANCE INT,
    PATERNITY_LEAVE_ENTITLE INT,
    LOP_OVERDRAFT INT
);
