server:
  port: 0
spring:
  cloud:
    stream:
      bindings:
        testConsumer-in-0:
          destination: stringsupplier
          group: stringsupplier-group
  rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest