server:
  port: 0
spring:
  application:
    name: lms-email-service
  config:
    import: optional:configserver:http://localhost:5555

management:
  endpoints:
    web:
      exposure:
        include: refresh