-- liquibase formatted sql

-- changeset Sarthak:1678898835087-10
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_schema = 'LMSATTENDANCESERVICE' AND table_name = 'ATTENDANCE';
CREATE TABLE ATTENDANCE (
  EMPLOYEE_ID VARCHAR(255) NOT NULL,
  DATE DATE NOT NULL,
  IN_TIME TIME,
  OUT_TIME TIME,
  DURATION BIGINT,
  ATTENDANCE_RECORD_TYPE VARCHAR(50) NOT NULL,
  APPROVAL_STATUS VARCHAR(20),
  APPROVED_BY VARCHAR(255),
  COMMENTS VARCHAR(255),
  PRIMARY KEY (EMPLOYEE_ID, DATE)
);
